"""
Attendance Distribution Component

Purpose
-------
Renders the attendance distribution section for the Attendance Analytics
workspace.

Responsibilities
----------------
- Display attendance distribution chart.
- Display attendance distribution table.
- Delegate formatting to presentation utilities.

Architectural Rules
-------------------
- Presentation only.
- No business logic.
- No analytics calculations.
"""

from __future__ import annotations

# ============================================================================
# Standard Library Imports
# ============================================================================
from collections import Counter
from typing import Any, cast

# ============================================================================
# Local Imports
# ============================================================================
from src.presentation.components.common import (
    charts,
    metric_cards,
    tables,
)
from src.presentation.utils import formatters

# ============================================================================
# Attendance Distribution
# ============================================================================


def render(
    attendance: dict[str, Any],
) -> None:
    """
    Render the attendance distribution section.

    Parameters
    ----------
    attendance:
        Attendance summary generated by the application layer.
    """

    metric_cards.render_section_header(
        "Attendance Distribution",
        "Attendance classification breakdown.",
    )

    attendance_counts = cast(
        Counter[Any],
        attendance["attendance_types"],
    )

    attendance_dataframe = formatters.counter_to_dataframe(
        attendance_counts,
    )

    charts.render_bar_chart(
        attendance_dataframe,
        x="Category",
        y="Count",
        title="Attendance Distribution",
    )

    tables.render_dataframe(
        attendance_dataframe,
    )
